project:
  type: website

website:
  title: "VAA Team 13"
  navbar:
    logo: images/ecowatt.png
    left:
      - href: index.qmd
        text: "EcoWatt Initiative"
        
    right:
      - text: "The Team"
        href: about.html
      - text: "Proposal"
        href: proposal.html
      - text: "Prototype"
        href: prototype.html
      - text: "User Guide"
        href: User_Guide.pdf
      - text: "Shiny App"
        href: https://chaizhixuan.shinyapps.io/project1/
      - text: "Poster"
        href: Poster.jpg
      - icon: github
        href: https://github.com/czx0727/ISSS608_Project
      - icon: github
        href: https://github.com/czx0727/ISSS608_Project_Shiny
      
format:
  html:
    theme: materia
    css: styles.css
    toc: true

editor: visual

