project:
  type: website

website:
  title: "VAA Team 13"
  navbar:
    left:
      - href: index.qmd
        text: "Project Title"
        
    right:
      - text: "The Team"
        href: about.qmd
      - text: "Proposal"
        href: proposal.qmd
      - text: "Prototype"
        href: prototype.qmd
      - text: "User Guide"
        href: user_guide.qmd
      - text: "Shiny App"
        href: shin_app.qmd
      - text: "Poster"
        href: poster.qmd
      
format:
  html:
    theme: superhero
    css: styles.css
    toc: true

editor: visual

