project:
  type: website

website:
  title: "VAA Team 13"
  navbar:
    left:
      - href: index.qmd
        text: "EcoWatt Initiative"
        
    right:
      - text: "The Team"
        href: about.html
      - text: "Proposal"
        href: proposal.html
      - text: "Prototype"
        href: prototype.html
      - text: "User Guide"
        href: user_guide.html
      - text: "Shiny App"
        href: shiny.qmd
      - text: "Poster"
        href: poster.html
      
format:
  html:
    theme: materia
    css: styles.css
    toc: true

editor: visual

